-- Platinum Pulse × VOID Creator Hub
-- COMPLETE replacement database setup, including Arranged Battle Booking.
-- WARNING: running this deletes existing creator totals, daily data and
-- arranged battle bookings/matches.
-- It does not delete the admin user in Supabase Authentication.

begin;

drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user() cascade;
drop function if exists public.is_admin() cascade;
drop function if exists public.normalise_battle_username() cascade;
drop function if exists public.normalise_battle_photo_row() cascade;
drop table if exists public.battle_match_entries cascade;
drop table if exists public.battle_bookings cascade;
drop table if exists public.battle_matches cascade;
drop table if exists public.creator_battle_photos cascade;
drop table if exists public.creator_metric_snapshots cascade;
drop table if exists public.creator_daily_metrics cascade;
drop table if exists public.creator_metrics cascade;
drop table if exists public.profiles cascade;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  display_name text,
  role text not null default 'creator' check (role in ('creator', 'admin')),
  created_at timestamptz not null default now()
);

create table public.creator_metrics (
  id bigint generated by default as identity primary key,
  username text unique not null,
  creator_id text,
  data_period text not null default '',
  group_name text,
  manager text,
  diamonds bigint not null default 0 check (diamonds >= 0),
  live_minutes integer not null default 0 check (live_minutes >= 0),
  live_duration text not null default '0m',
  valid_live_days integer not null default 0 check (valid_live_days >= 0),
  live_streams integer not null default 0 check (live_streams >= 0),
  matches integer not null default 0 check (matches >= 0),
  avatar_url text,
  updated_at timestamptz not null default now(),
  constraint reserved_admin_username check (lower(trim(leading '@' from username)) <> 'ppn777')
);



create table public.creator_daily_metrics (
  id bigint generated by default as identity primary key,
  username text not null,
  metric_date date not null,
  diamonds bigint not null default 0 check (diamonds >= 0),
  live_minutes integer not null default 0 check (live_minutes >= 0),
  live_duration text not null default '0m',
  valid_live_days integer not null default 0 check (valid_live_days >= 0),
  updated_at timestamptz not null default now(),
  unique (username, metric_date),
  constraint reserved_daily_admin_username check (lower(trim(leading '@' from username)) <> 'ppn777')
);

create table public.creator_metric_snapshots (
  id bigint generated by default as identity primary key,
  username text not null,
  period_start date not null,
  period_end date not null,
  diamonds bigint not null default 0 check (diamonds >= 0),
  live_minutes integer not null default 0 check (live_minutes >= 0),
  valid_live_days integer not null default 0 check (valid_live_days >= 0),
  live_streams integer not null default 0 check (live_streams >= 0),
  matches integer not null default 0 check (matches >= 0),
  source_name text not null default '',
  imported_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (username, period_start, period_end),
  constraint valid_snapshot_period check (period_end >= period_start),
  constraint reserved_snapshot_admin_username check (lower(trim(leading '@' from username)) <> 'ppn777')
);

create or replace function public.normalise_creator_row()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.username := lower(trim(leading '@' from trim(new.username)));
  new.updated_at := now();
  return new;
end;
$$;

create trigger normalise_creator_metrics
before insert or update on public.creator_metrics
for each row execute function public.normalise_creator_row();

create trigger normalise_creator_daily_metrics
before insert or update on public.creator_daily_metrics
for each row execute function public.normalise_creator_row();

create trigger normalise_creator_metric_snapshots
before insert or update on public.creator_metric_snapshots
for each row execute function public.normalise_creator_row();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  is_agency_admin boolean;
  requested_username text;
begin
  is_agency_admin := lower(coalesce(new.email, '')) = 'admin@login.platinumpulse.app';
  requested_username := case
    when is_agency_admin then 'agency-controls'
    else lower(coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)))
  end;

  insert into public.profiles (id, username, display_name, role)
  values (
    new.id,
    requested_username,
    case when is_agency_admin then 'Agency Controls'
      else coalesce(new.raw_user_meta_data ->> 'display_name', requested_username)
    end,
    case when is_agency_admin then 'admin' else 'creator' end
  )
  on conflict (id) do update set
    username = excluded.username,
    display_name = excluded.display_name,
    role = excluded.role;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

alter table public.profiles enable row level security;
alter table public.creator_metrics enable row level security;
alter table public.creator_daily_metrics enable row level security;
alter table public.creator_metric_snapshots enable row level security;

create policy "Authenticated users can read their profile"
on public.profiles for select to authenticated
using (id = auth.uid() or public.is_admin());

create policy "Everyone can read creator totals"
on public.creator_metrics for select to anon, authenticated
using (true);

create policy "Everyone can read creator daily data"
on public.creator_daily_metrics for select to anon, authenticated
using (true);

create policy "Admins can read stacked creator uploads"
on public.creator_metric_snapshots for select to authenticated
using (public.is_admin());



create policy "Admins can insert creator totals"
on public.creator_metrics for insert to authenticated
with check (public.is_admin());

create policy "Admins can update creator totals"
on public.creator_metrics for update to authenticated
using (public.is_admin()) with check (public.is_admin());

create policy "Admins can delete creator totals"
on public.creator_metrics for delete to authenticated
using (public.is_admin());

create policy "Admins can insert creator daily data"
on public.creator_daily_metrics for insert to authenticated
with check (public.is_admin());

create policy "Admins can update creator daily data"
on public.creator_daily_metrics for update to authenticated
using (public.is_admin()) with check (public.is_admin());

create policy "Admins can delete creator daily data"
on public.creator_daily_metrics for delete to authenticated
using (public.is_admin());

create policy "Admins can insert stacked creator uploads"
on public.creator_metric_snapshots for insert to authenticated
with check (public.is_admin());

create policy "Admins can update stacked creator uploads"
on public.creator_metric_snapshots for update to authenticated
using (public.is_admin()) with check (public.is_admin());

create policy "Admins can delete stacked creator uploads"
on public.creator_metric_snapshots for delete to authenticated
using (public.is_admin());

grant select on public.creator_metrics, public.creator_daily_metrics to anon, authenticated;
grant insert, update, delete on public.creator_metrics, public.creator_daily_metrics to authenticated;
grant select, insert, update, delete on public.creator_metric_snapshots to authenticated;
grant usage, select on sequence public.creator_metrics_id_seq, public.creator_daily_metrics_id_seq, public.creator_metric_snapshots_id_seq to authenticated;
grant select on public.profiles to authenticated;

insert into public.profiles (id, username, display_name, role)
select id, 'agency-controls', 'Agency Controls', 'admin'
from auth.users
where lower(email) = 'admin@login.platinumpulse.app'
on conflict (id) do update set
  username = excluded.username,
  display_name = excluded.display_name,
  role = excluded.role;



-- ================= AUTOMATIC DAILY BREAKDOWN =================
create or replace function public.rebuild_creator_daily_metrics()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  rebuilt_rows integer := 0;
begin
  -- Browser/app calls must come from the agency admin. Running this manually as
  -- the database owner from the SQL editor is also allowed (auth.uid() is null).
  if auth.uid() is not null and not public.is_admin() then
    raise exception 'Only an agency admin can rebuild creator daily metrics';
  end if;

  create temporary table _rebuilt_creator_daily (
    username text not null,
    metric_date date not null,
    diamonds bigint not null,
    live_minutes integer not null,
    live_duration text not null,
    valid_live_days integer not null,
    primary key (username, metric_date)
  ) on commit drop;

  -- Rebuild each creator independently for each cumulative period start.
  -- A daily value is only calculated when:
  --   1) the snapshot itself is a one-day period, OR
  --   2) yesterday's cumulative snapshot exists for the SAME period_start.
  -- Therefore a missing export is never incorrectly dumped into one day.
  insert into _rebuilt_creator_daily (username, metric_date, diamonds, live_minutes, live_duration, valid_live_days)
  with ordered as (
    select
      lower(trim(leading '@' from trim(s.username))) as username,
      s.period_start,
      s.period_end,
      greatest(0, coalesce(s.diamonds, 0))::bigint as diamonds,
      greatest(0, coalesce(s.live_minutes, 0))::integer as live_minutes,
      greatest(0, coalesce(s.valid_live_days, 0))::integer as valid_live_days,
      lag(s.period_end) over (
        partition by lower(trim(leading '@' from trim(s.username))), s.period_start
        order by s.period_end
      ) as previous_end,
      lag(greatest(0, coalesce(s.diamonds, 0))) over (
        partition by lower(trim(leading '@' from trim(s.username))), s.period_start
        order by s.period_end
      ) as previous_diamonds,
      lag(greatest(0, coalesce(s.live_minutes, 0))) over (
        partition by lower(trim(leading '@' from trim(s.username))), s.period_start
        order by s.period_end
      ) as previous_live_minutes,
      lag(greatest(0, coalesce(s.valid_live_days, 0))) over (
        partition by lower(trim(leading '@' from trim(s.username))), s.period_start
        order by s.period_end
      ) as previous_valid_live_days
    from public.creator_metric_snapshots s
  ),
  calculated as (
    select
      username,
      period_start,
      period_end as metric_date,
      case
        when period_start = period_end then diamonds
        when previous_end = (period_end - 1) then greatest(0, diamonds - coalesce(previous_diamonds, 0))
        else null
      end::bigint as daily_diamonds,
      case
        when period_start = period_end then live_minutes
        when previous_end = (period_end - 1) then greatest(0, live_minutes - coalesce(previous_live_minutes, 0))
        else null
      end::integer as daily_live_minutes,
      case
        when period_start = period_end then valid_live_days
        when previous_end = (period_end - 1) then greatest(0, valid_live_days - coalesce(previous_valid_live_days, 0))
        else null
      end::integer as daily_valid_live_days
    from ordered
  ),
  deduped as (
    select distinct on (username, metric_date)
      username,
      metric_date,
      daily_diamonds,
      daily_live_minutes,
      daily_valid_live_days
    from calculated
    where daily_diamonds is not null and daily_live_minutes is not null and daily_valid_live_days is not null
    order by username, metric_date, period_start desc
  )
  select
    username,
    metric_date,
    daily_diamonds,
    daily_live_minutes,
    case
      when daily_live_minutes >= 60 then
        (daily_live_minutes / 60)::text || 'h ' || (daily_live_minutes % 60)::text || 'm'
      else daily_live_minutes::text || 'm'
    end,
    daily_valid_live_days
  from deduped;

  -- Remove only daily rows covered by saved snapshot ranges. This clears stale
  -- calculations from previous importer versions while leaving unrelated data alone.
  delete from public.creator_daily_metrics d
  using (
    select
      lower(trim(leading '@' from trim(username))) as username,
      period_start,
      max(period_end) as period_end
    from public.creator_metric_snapshots
    group by lower(trim(leading '@' from trim(username))), period_start
  ) r
  where lower(trim(leading '@' from trim(d.username))) = r.username
    and d.metric_date between r.period_start and r.period_end;

  insert into public.creator_daily_metrics (username, metric_date, diamonds, live_minutes, live_duration, valid_live_days)
  select username, metric_date, diamonds, live_minutes, live_duration, valid_live_days
  from _rebuilt_creator_daily
  on conflict (username, metric_date) do update set
    diamonds = excluded.diamonds,
    live_minutes = excluded.live_minutes,
    live_duration = excluded.live_duration,
    valid_live_days = excluded.valid_live_days,
    updated_at = now();

  get diagnostics rebuilt_rows = row_count;
  return rebuilt_rows;
end;
$$;

revoke all on function public.rebuild_creator_daily_metrics() from public;
grant execute on function public.rebuild_creator_daily_metrics() to authenticated;

-- ================= ARRANGED BATTLE BOOKING =================
-- Merged in from the standalone "battle-booker" tool. Creators book their own
-- availability and the admin pairs bookings into matches. Creators are not
-- Supabase Auth users (same as the rest of this hub), so — matching the
-- original battle-booker's documented trust model — these four tables stay
-- readable and writable by anyone holding the published anon key. The admin
-- pairing/unpairing/clearing controls are only reachable in the app after
-- signing in with the one shared ppn777 admin login.

create table public.battle_matches (
  id bigint generated by default as identity primary key,
  battle_type text not null check (battle_type = '1v1'),
  created_at timestamptz not null default now()
);

create table public.battle_bookings (
  id bigint generated by default as identity primary key,
  username text not null,
  battle_date date not null,
  battle_time text not null,
  battle_type text not null check (battle_type = '1v1'),
  paired_match_id bigint references public.battle_matches(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint reserved_booking_admin_username check (lower(trim(leading '@' from username)) <> 'ppn777')
);

create table public.battle_match_entries (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.battle_matches(id) on delete cascade,
  booking_id bigint references public.battle_bookings(id) on delete set null,
  username text not null,
  team text not null check (team in ('A', 'B')),
  battle_date date not null,
  battle_time text not null
);

create table public.creator_battle_photos (
  username text primary key,
  photo_data text not null,
  updated_at timestamptz not null default now(),
  constraint reserved_photo_admin_username check (username <> 'ppn777')
);

create index battle_bookings_username_idx on public.battle_bookings (username);
create index battle_bookings_date_idx on public.battle_bookings (battle_date);
create index battle_match_entries_username_idx on public.battle_match_entries (username);
create index battle_match_entries_date_idx on public.battle_match_entries (battle_date);
create index battle_match_entries_match_idx on public.battle_match_entries (match_id);

create or replace function public.normalise_battle_username()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.username := lower(trim(leading '@' from trim(new.username)));
  return new;
end;
$$;

create or replace function public.normalise_battle_photo_row()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.username := lower(trim(leading '@' from trim(new.username)));
  new.updated_at := now();
  return new;
end;
$$;

create trigger normalise_battle_bookings
before insert or update on public.battle_bookings
for each row execute function public.normalise_battle_username();

create trigger normalise_battle_match_entries
before insert or update on public.battle_match_entries
for each row execute function public.normalise_battle_username();

create trigger normalise_creator_battle_photos
before insert or update on public.creator_battle_photos
for each row execute function public.normalise_battle_photo_row();

alter table public.battle_matches enable row level security;
alter table public.battle_bookings enable row level security;
alter table public.battle_match_entries enable row level security;
alter table public.creator_battle_photos enable row level security;

create policy "Anyone can read arranged battle matches"
on public.battle_matches for select to anon, authenticated using (true);
create policy "Anyone can create arranged battle matches"
on public.battle_matches for insert to anon, authenticated with check (true);
create policy "Anyone can delete arranged battle matches"
on public.battle_matches for delete to anon, authenticated using (true);

create policy "Anyone can read arranged battle bookings"
on public.battle_bookings for select to anon, authenticated using (true);
create policy "Anyone can create arranged battle bookings"
on public.battle_bookings for insert to anon, authenticated with check (true);
create policy "Anyone can update arranged battle bookings"
on public.battle_bookings for update to anon, authenticated using (true) with check (true);
create policy "Anyone can delete arranged battle bookings"
on public.battle_bookings for delete to anon, authenticated using (true);

create policy "Anyone can read arranged battle entries"
on public.battle_match_entries for select to anon, authenticated using (true);
create policy "Anyone can create arranged battle entries"
on public.battle_match_entries for insert to anon, authenticated with check (true);
create policy "Anyone can delete arranged battle entries"
on public.battle_match_entries for delete to anon, authenticated using (true);

create policy "Anyone can read creator battle photos"
on public.creator_battle_photos for select to anon, authenticated using (true);
create policy "Anyone can upload their own battle photo"
on public.creator_battle_photos for insert to anon, authenticated with check (true);
create policy "Anyone can update their own battle photo"
on public.creator_battle_photos for update to anon, authenticated using (true) with check (true);

grant select, insert, update, delete on public.battle_bookings, public.battle_matches, public.battle_match_entries to anon, authenticated;
grant select, insert, update on public.creator_battle_photos to anon, authenticated;
grant usage, select on sequence public.battle_bookings_id_seq, public.battle_matches_id_seq, public.battle_match_entries_id_seq to anon, authenticated;

do $$
begin
  if not exists (
    select 1 from auth.users where lower(email) = 'admin@login.platinumpulse.app'
  ) then
    raise exception
      'Create admin@login.platinumpulse.app in Authentication first with password ppn777 and Auto Confirm enabled, then rerun this SQL.';
  end if;
end;
$$;

commit;
