-- V31: Quick Manager FAQ escalation, private creator threads, manager accounts and notifications.
-- Safe migration: does not delete creator performance or arranged battle data.
begin;

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('creator','manager','admin'));

create or replace function public.is_staff()
returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.profiles where id=auth.uid() and role in ('admin','manager'));
$$;
revoke all on function public.is_staff() from public;
grant execute on function public.is_staff() to authenticated;

-- Keep Owner-only data controls unchanged. Managers are deliberately NOT added to is_admin().

create table if not exists public.support_messages (
 id bigint generated by default as identity primary key,
 creator_username text not null,
 sender_role text not null check(sender_role in ('creator','manager','admin','bot')),
 sender_name text not null default '',
 message text not null,
 created_at timestamptz not null default now()
);
create index if not exists support_messages_creator_idx on public.support_messages(lower(creator_username),created_at);

create table if not exists public.hub_notifications (
 id bigint generated by default as identity primary key,
 recipient_username text,
 recipient_role text,
 type text not null default 'info',
 title text not null,
 body text not null default '',
 link_view text,
 read_at timestamptz,
 created_at timestamptz not null default now()
);
create index if not exists hub_notifications_recipient_idx on public.hub_notifications(lower(recipient_username),created_at desc);

alter table public.support_messages enable row level security;
alter table public.hub_notifications enable row level security;
-- Chat/notification access is intentionally server-route only (service role). No anon grants.
revoke all on public.support_messages, public.hub_notifications from anon, authenticated;

-- Managers need read access to the creator directory and arranged-battle data.
-- Existing public read policies already cover creator totals/battle rows.
-- Pairing writes are currently public in this app, so the UI limits pairing to staff.

grant select on public.profiles to authenticated;

-- Update new-auth-user role handling so manager metadata is respected.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
declare requested_role text; requested_username text; is_agency_admin boolean;
begin
 is_agency_admin := lower(coalesce(new.email,''))='admin@login.platinumpulse.app';
 requested_role := case when is_agency_admin then 'admin' when coalesce(new.raw_user_meta_data->>'role','')='manager' then 'manager' else 'creator' end;
 requested_username := case when is_agency_admin then 'agency-controls' else lower(coalesce(new.raw_user_meta_data->>'username',split_part(new.email,'@',1))) end;
 insert into public.profiles(id,username,display_name,role) values(new.id,requested_username,case when is_agency_admin then 'Owner' else coalesce(new.raw_user_meta_data->>'display_name',requested_username) end,requested_role)
 on conflict(id) do update set username=excluded.username,display_name=excluded.display_name,role=excluded.role;
 return new;
end;$$;

commit;
