-- V32 safe migration: manager groups + creator dashboard campaign banners.
-- Run AFTER V31-QUICK-MANAGER-CHAT.sql. Does not delete creator data.
begin;
alter table public.profiles add column if not exists manager_group text not null default '';
create table if not exists public.campaign_banners (
 id bigint generated by default as identity primary key,
 title text not null,
 image_url text not null,
 storage_path text not null default '',
 active boolean not null default true,
 created_at timestamptz not null default now()
);
alter table public.campaign_banners enable row level security;
revoke all on public.campaign_banners from anon, authenticated;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('campaign-banners','campaign-banners',true,8388608,array['image/jpeg','image/png','image/webp'])
on conflict(id) do update set public=true,file_size_limit=8388608,allowed_mime_types=excluded.allowed_mime_types;
commit;
