import {NextResponse} from 'next/server';
import {serverClient,staffFromRequest} from '../_server';
const clean=(v:unknown)=>String(v||'').trim().replace(/^@/,'').toLowerCase();
async function checkedTikTok(db:ReturnType<typeof serverClient>,value:unknown){
 const username=clean(value); if(!username)return null;
 if(!/^[a-z0-9._]{1,64}$/.test(username))throw new Error('Enter a valid TikTok username.');
 const {data,error}=await db.from('creator_metrics').select('username').ilike('username',username.replace(/[_%\\]/g,'\\$&')).limit(1);
 if(error)throw error;if(!data?.length)throw new Error('That TikTok username is not in the uploaded creator data.');
 return clean(data[0].username);
}
export async function GET(request:Request){try{const staff=await staffFromRequest(request);if(!staff||staff.role!=='admin')return NextResponse.json({error:'Owner access required.'},{status:403});const db=serverClient();const managers=[];const pageSize=1000;for(let from=0;;from+=pageSize){const {data,error}=await db.from('profiles').select('id,username,display_name,role,manager_group,tiktok_username,created_at').eq('role','manager').order('created_at',{ascending:false}).order('id').range(from,from+pageSize-1);if(error)throw error;managers.push(...(data||[]));if(!data||data.length<pageSize)break;}return NextResponse.json({managers});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Could not load managers.'},{status:500});}}
export async function POST(request:Request){try{const staff=await staffFromRequest(request);if(!staff||staff.role!=='admin')return NextResponse.json({error:'Owner access required.'},{status:403});const body=await request.json();const username=clean(body.username).replace(/[^a-z0-9._-]/g,'');const password=String(body.password||'');const display=String(body.display_name||username).trim();const manager_group=String(body.manager_group||'').trim();if(!username||password.length<6)return NextResponse.json({error:'Use a manager username and a password of at least 6 characters.'},{status:400});const db=serverClient();const tiktok_username=await checkedTikTok(db,body.tiktok_username);const email=`${username}@manager.platinumpulse.app`;const {data,error}=await db.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{username,display_name:display,manager_group}});if(error||!data.user)return NextResponse.json({error:error?.message||'Could not create manager.'},{status:400});const {error:profileError}=await db.from('profiles').upsert({id:data.user.id,username,display_name:display,role:'manager',manager_group,tiktok_username});if(profileError){await db.auth.admin.deleteUser(data.user.id);throw profileError;}return NextResponse.json({ok:true});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Could not create manager.'},{status:400});}}
export async function PATCH(request:Request){try{const staff=await staffFromRequest(request);if(!staff||staff.role!=='admin')return NextResponse.json({error:'Owner access required.'},{status:403});const body=await request.json();const db=serverClient();const {data:target}=await db.from('profiles').select('id,role').eq('id',String(body.id||staff.id)).single();if(!target||!['manager','admin'].includes(target.role))return NextResponse.json({error:'Staff account not found.'},{status:404});const tiktok_username=await checkedTikTok(db,body.tiktok_username);const {error}=await db.from('profiles').update({tiktok_username}).eq('id',target.id);if(error)throw error;return NextResponse.json({ok:true,tiktok_username});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Could not link TikTok.'},{status:400});}}
export async function DELETE(request:Request){try{const staff=await staffFromRequest(request);if(!staff||staff.role!=='admin')return NextResponse.json({error:'Owner access required.'},{status:403});const {id}=await request.json();const db=serverClient();const {data:target}=await db.from('profiles').select('role').eq('id',String(id)).single();if(target?.role!=='manager')return NextResponse.json({error:'Manager account not found.'},{status:404});const {error}=await db.auth.admin.deleteUser(String(id));if(error)throw error;return NextResponse.json({ok:true});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Could not remove manager.'},{status:500});}}
