'use client';
import { useEffect, useMemo, useState } from 'react';
import { Bot, ChevronRight, LifeBuoy, MessageCircle, Search, Send, UserRound } from 'lucide-react';
import { LIVE_FAQ, findFaqAnswer } from './faq-data';
import type { Profile } from './shared';
import { supabase } from './supabase';

type SupportMessage={id:number;creator_username:string;sender_role:string;sender_name:string;message:string;created_at:string};
async function authHeaders(): Promise<Headers>{const h=new Headers();const token=(await supabase?.auth.getSession())?.data.session?.access_token;if(token)h.set('Authorization',`Bearer ${token}`);return h}

export function QuickManager({profile}:{profile:Profile}){
 const [messages,setMessages]=useState<{who:'me'|'bot';text:string}[]>([{who:'bot',text:'👋 Hi! I’m Quick Manager. Ask me a simple TikTok LIVE question like “What are frags?”, “What’s a glove?”, “How do campaigns work?” or “How can I grow my LIVE?”'}]);
 const [input,setInput]=useState(''); const [lastQuestion,setLastQuestion]=useState(''); const [sent,setSent]=useState(false); const [search,setSearch]=useState('');
 const filtered=useMemo(()=>LIVE_FAQ.filter(x=>(x.title+' '+x.keywords.join(' ')).toLowerCase().includes(search.toLowerCase())).slice(0,8),[search]);
 const ask=(text:string)=>{const q=text.trim();if(!q)return;setMessages(m=>[...m,{who:'me',text:q}]);setInput('');setSent(false);setLastQuestion(q);const found=findFaqAnswer(q);setTimeout(()=>setMessages(m=>[...m,{who:'bot',text:found?.answer||'I couldn’t find a confident FAQ answer for that one. You can send it privately to management and a manager will reply in your support chat.'}]),120)};
 const escalate=async()=>{if(!lastQuestion)return;const r=await fetch('/api/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({creator:profile.username,message:lastQuestion})});if(r.ok)setSent(true)};
 return <>
  <section className="page-heading"><div><p className="eyebrow">Instant creator help</p><h1>Message Manager/Ban Help</h1><p>Ask simple TikTok LIVE questions and get an instant answer from the approved creator FAQ.</p></div></section>
  <div className="manager-help-grid">
   <section className="panel quick-chat-panel"><div className="quick-chat-head"><Bot/><div><h2>Quick Manager</h2><p>FAQ assistant</p></div></div><div className="quick-chat-messages">{messages.map((m,i)=><div key={i} className={`quick-msg ${m.who}`}><b>{m.who==='bot'?'Quick Manager':'You'}</b><span>{m.text}</span></div>)}</div>{lastQuestion&&<div className="escalate-row"><button className="secondary-button" onClick={escalate} disabled={sent}><LifeBuoy size={16}/>{sent?'Sent privately to management':'Still need help? Ask management'}</button></div>}<form className="quick-chat-input" onSubmit={e=>{e.preventDefault();ask(input)}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about TikTok LIVE…"/><button className="primary-button"><Send size={17}/></button></form></section>
   <section className="panel"><h2>Popular questions</h2><div className="search-box faq-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search the FAQ"/></div><div className="faq-shortcuts">{filtered.map(item=><button key={item.id} onClick={()=>ask(item.title)}><span>{item.title}</span><ChevronRight size={17}/></button>)}</div></section>
  </div>
  <CreatorSupportChat profile={profile}/>
 </>
}

export function CreatorSupportChat({profile}:{profile:Profile}){const [items,setItems]=useState<SupportMessage[]>([]);const [text,setText]=useState('');const load=()=>fetch(`/api/support?creator=${encodeURIComponent(profile.username)}`).then(r=>r.json()).then(x=>setItems(x.messages||[]));useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[]);const send=async(e:React.FormEvent)=>{e.preventDefault();if(!text.trim())return;await fetch('/api/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({creator:profile.username,message:text})});setText('');load()};return <section className="panel support-thread"><div className="quick-chat-head"><MessageCircle/><div><h2>Private management chat</h2><p>Only your creator login and management see this thread.</p></div></div><div className="support-messages">{!items.length&&<div className="empty-state">No management messages yet. Use “Still need help?” above or type a question here.</div>}{items.map(x=><div className={`support-bubble ${x.sender_role==='creator'?'mine':'staff'}`} key={x.id}><b>{x.sender_role==='creator'?'You':x.sender_name||'Management'}</b><span>{x.message}</span><small>{new Date(x.created_at).toLocaleString()}</small></div>)}</div><form className="quick-chat-input" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Message management privately…"/><button className="primary-button"><Send size={17}/></button></form></section>}

export function StaffInbox({profile}:{profile:Profile}){const [items,setItems]=useState<SupportMessage[]>([]);const [creator,setCreator]=useState('');const [text,setText]=useState('');const load=async()=>{const h=await authHeaders();const r=await fetch('/api/support',{headers:h});const x=await r.json();setItems(x.messages||[])};useEffect(()=>{load();const t=setInterval(load,8000);return()=>clearInterval(t)},[]);const creators=[...new Set(items.map(x=>x.creator_username))];const active=creator||creators[0]||'';const send=async(e:React.FormEvent)=>{e.preventDefault();if(!active||!text.trim())return;const h=await authHeaders();await fetch('/api/support',{method:'POST',headers:(()=>{h.set('Content-Type','application/json');return h})(),body:JSON.stringify({creator:active,message:text})});setText('');load()};return <><section className="page-heading"><div><p className="eyebrow">Creator support</p><h1>Manager Inbox</h1><p>Reply to creators who need help. Every creator has a separate private thread.</p></div></section><div className="staff-inbox"><section className="panel staff-thread-list"><h3>Creator chats</h3>{!creators.length&&<div className="empty-state">No creator support messages yet.</div>}{creators.map(c=><button className={active===c?'active':''} key={c} onClick={()=>setCreator(c)}><UserRound size={17}/><span>@{c}</span></button>)}</section><section className="panel support-thread"><div className="quick-chat-head"><MessageCircle/><div><h2>{active?`@${active}`:'Choose a creator'}</h2><p>{profile.role==='admin'?'Owner reply':'Manager reply'}</p></div></div><div className="support-messages">{items.filter(x=>x.creator_username===active).map(x=><div className={`support-bubble ${x.sender_role==='creator'?'creator':'staff'}`} key={x.id}><b>{x.sender_role==='creator'?`@${x.creator_username}`:x.sender_name}</b><span>{x.message}</span><small>{new Date(x.created_at).toLocaleString()}</small></div>)}</div>{active&&<form className="quick-chat-input" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder={`Reply privately to @${active}…`}/><button className="primary-button"><Send size={17}/></button></form>}</section></div></>}
